"""initial revision

Revision ID: 701aa7ea6e2d
Revises: ab8ca6ee9963
Create Date: 2022-01-28 11:29:15.092157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701aa7ea6e2d'
down_revision = 'ab8ca6ee9963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_edited', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_edited')
    # ### end Alembic commands ###
