"""initial revision

Revision ID: ab8ca6ee9963
Revises: 4421ac8027a5
Create Date: 2022-01-20 13:04:42.464001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab8ca6ee9963'
down_revision = '4421ac8027a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
