"""initial revision

Revision ID: b918ad6ffeee
Revises: dd7b9eb80cd1
Create Date: 2022-02-03 18:33:54.205397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b918ad6ffeee'
down_revision = 'dd7b9eb80cd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('ip_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'ip_address')
    # ### end Alembic commands ###
