"""initial revision

Revision ID: bf7b70592bb5
Revises: ba400a6c9d66
Create Date: 2022-01-05 19:21:14.396813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf7b70592bb5'
down_revision = 'ba400a6c9d66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
