"""initial revision

Revision ID: c697d681107f
Revises: bf7b70592bb5
Create Date: 2022-01-05 19:22:23.277714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c697d681107f'
down_revision = 'bf7b70592bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
