"""initial revision

Revision ID: dccccffcf610
Revises: c697d681107f
Create Date: 2022-01-07 09:58:36.786829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dccccffcf610'
down_revision = 'c697d681107f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('portrait_filename', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('portrait_url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'portrait_url')
    op.drop_column('user', 'portrait_filename')
    # ### end Alembic commands ###
