"""initial revision

Revision ID: dd7b9eb80cd1
Revises: a825289a3a2f
Create Date: 2022-02-03 15:00:08.855314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd7b9eb80cd1'
down_revision = 'a825289a3a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
